<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>AgentSkills.Api</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\AgentSkills.Application\AgentSkills.Application.csproj" />
    <ProjectReference Include="..\..\AgentSkills.Infrastructure\AgentSkills.Infrastructure.csproj" />
    <ProjectReference Include="..\..\AgentSkills.ServiceDefaults\AgentSkills.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
